title: Yash's Pages 
description: "Class of 2025"
owner_name: John Mortensen
github_username: nighthawkcoders
github_repo: "yash1_2025" 
baseurl: "/yash1_2025"

future: true
remote_theme: pages-themes/cayman@v0.2.0
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/liverpool.md
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/journey.md
  - README4YML.md


